### PR TITLE
Recursion

### PR DESCRIPTION
**Pull request by jakehschwartz**

### CODE REVIEW

**Comment by gytdau** [comment]
Wonderful. We probably shouldn't merge yet until we've added a bit more (and that TODO note would be visible to everyone)

I'll work a bit on it tomorrow.

**Comment by jakehschwartz** [comment]
Ok. I thought it isn't visible until it goes onto the gh-pages branch.

**Comment by gytdau** [comment]
Good point, it isn't: maybe we should rename the master branch to something else like 'dev'.

**Comment by gytdau** [comment]
You don't have to add the heading code snippets.

Sorry, I should've put this in the readme: http://gytdau.github.io/clarifycode/?view=sample.
This is the sample folder, and you can see the code editor there.

**Pull request merged**
